### ISSUE TITLE
Nest.land fails to install

### ISSUE THREAD

**Issue by asplunds** [nestdotland/nest#18]
# 🐛 Bug Report

The forst instruktion in the [readme](https://github.com/nestdotland/nest/blob/main/README.md) "INSTALL" does not work.

## To Reproduce

1. Run `deno install -Af https://nest.land/-/nest/nest.ts`

## Expected behavior

Nest.land installs successfully

## Actual Behavior

Deno throws error "error: An unsupported media type was attempted to be imported as a module." because `https://nest.land/-/nest/nest.ts` returns 404.

## Environment

- CLI version: -
- Deno version: deno 1.7.1
- Operating system and version: Windows 10 v88.0.4324.150

## Additional context

\-

**Comment by oganexon** [comment]
Hi @asplunds 
This repo is a WIP for the new CLI of nest, I'll add this on the readme to make it clearer, sorry for the confusion.
Until the stable release of nest, the current CLI is [eggs](https://github.com/nestdotland/eggs).
